/*
 *	@Author: Huan Tran
 *	@Date: 04/05/2020
 *	@Note: The program is to demonstrate how to manipulate pixel data in a Mat structs
 *	User can pick the frame to be showed to be from the webcam or a generated blue background
 *	The program will try to draw a moving white box onto the background to show how to manipulate the matrix
 *	The current time will also be written on to the bottom right corner of the frame
 *	Terminating the program by click on the image window and press any keys.\
 * 	Spinnaker example folder /usr/src/spinnaker
 *	Read file ./ActionCommand/ActionCommand.cpp to see example for getting timestamp
 *	Remember to increase USB commandline limit before running acquisition 
 *	https://www.flir.com/support-center/iis/machine-vision/application-note/understanding-usbfs-on-linux/
 */

#include <opencv2/core.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <string>
#include <iostream>
#include <ctime>

using namespace cv;
using namespace std;

#define WEBCAM 0
#define AUTOGENERATED 1

#define DEFAULT_TIME_X_POS 0
#define DEFAULT_TIME_Y_POS 450
#define DEFAULT_NUM_COLS 500
#define DEFAULT_NUM_ROWS 500
#define DEFAULT_IMAGE_TYPE CV_8UC3
#define DEFAULT_IMAGE_VALUE Scalar(255,0,0)
#define BOX_SIZE 50

string type2str(int type)
{
  string r;

  uchar depth = type & CV_MAT_DEPTH_MASK;
  uchar chans = 1 + (type >> CV_CN_SHIFT);

  switch ( depth ) {
    case CV_8U:  r = "8U"; break;
    case CV_8S:  r = "8S"; break;
    case CV_16U: r = "16U"; break;
    case CV_16S: r = "16S"; break;
    case CV_32S: r = "32S"; break;
    case CV_32F: r = "32F"; break;
    case CV_64F: r = "64F"; break;
    default:     r = "User"; break;
  }

  r += "C";
  r += (chans+'0');

  return r;
}
void drawRectangle(Mat& frame)
{
	static int lastRow=0,lastCol=0;
	// Move the box
	lastCol+=BOX_SIZE;
	if(lastCol>=frame.cols - BOX_SIZE)
	{
		lastCol=0;
		lastRow+=BOX_SIZE;
		if(lastRow >= frame.rows - BOX_SIZE)
		{
			lastRow=0;
		}
	}
	// Draw the box
	for(int i=0;i<BOX_SIZE;i++)
	{
		for(int j=0;j<BOX_SIZE;j++)
		{
			uchar* pixel = frame.ptr(lastRow+i,lastCol+j);
			pixel[0]=pixel[1]=pixel[2]=255;
		}
	}
}

void drawTime(Mat& frame)
{
	time_t theTime=time(nullptr);
	string myTime=string(asctime(localtime(&theTime)));
	putText(frame,myTime,Point(DEFAULT_TIME_X_POS,DEFAULT_TIME_Y_POS),FONT_HERSHEY_SIMPLEX,0.5,Scalar(255,255,255));
}

Mat getMatFromCam()
{
	// Open default camera
	static VideoCapture cap(0,CAP_DSHOW);
	Mat frame;
	// Generating a Mat from the webcam
	cap.read(frame);
	if(!cap.isOpened())
	{
		cerr<<"Error openning camera";
		return Mat(0,0,0);
	}
	if(frame.empty())
	{
		cerr<<"Error acquiring frame from camera";
		return Mat(0,0,0);
	}
	return frame;
}

Mat genMatAuto()
{
	Mat theMat(DEFAULT_NUM_ROWS,DEFAULT_NUM_COLS,DEFAULT_IMAGE_TYPE,DEFAULT_IMAGE_VALUE);
	return theMat;
}
int main(int n, char** args)
{
	Mat frame;
	int choice;
	// Pick your choice of input
	cout<<"Pick you choice of input ( 0 for webcame, other for auto-generated Mat ): ";
	cin>>choice;
	if(choice != WEBCAM)
	{
		choice = AUTOGENERATED;
	}
	// Wait for signal from user
	cout<<"Press any key to start capturing"<<endl;
	waitKey(0);
	while(1)
	{
		switch(choice)
		{
			case WEBCAM:
				frame=getMatFromCam();
				break;
			case AUTOGENERATED:
				frame=genMatAuto();
		}
		drawRectangle(frame);
		drawTime(frame);
		imshow("Picture", frame);
		if(waitKey(50)>=0)
		{
			// If key is pressed , exit
			break;
		}
		cout<<"Mat type: "<<type2str(frame.type())<<endl;
		frame.release();
	}
	return 0;
}